import type { NextApiHandler, NextApiRequest, NextApiResponse } from 'next';

const handler: NextApiHandler = async (
  request: NextApiRequest,
  response: NextApiResponse
) => {
  if (request.method === 'GET') {
    const page = Number(request.query.page);
    const data = response_mock(page);
    response.status(200).json(data);
  }
};

export default handler;

function response_mock(page: number) {
  switch (page) {
    case 1:
      return {
        hasNext: true,
        count: 100,
        data: [
          {
            id: 5310249108766720,
            alias: 'snail',
            title: '아가씨와 우렁총각',
            artists: [{ name: '제이드', role: 'writer', id: 'jade' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 1,
            previousRank: 1,
            updatedAt: 1610007388299,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5459019290705920,
            alias: 'ceos_crooked_love',
            title: '대표님의 삐뚤어진 사랑 [연재]',
            artists: [
              { name: 'Hongshu', role: 'scripter', id: 'hongshu' },
              { name: 'Rose Studio', role: 'painter', id: 'rosestudio' },
              { name: 'Nianhuarexiao', role: 'original', id: 'nianhuarexiao' },
              { name: '스토리숲', role: 'publisher', id: 'storySoop' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 15,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 2,
            previousRank: 4,
            updatedAt: 1620023306380,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5849944865636352,
            alias: 'pencil',
            title: '연필의 각도',
            artists: [{ name: '홍자', role: 'writer', id: 'hongja' }],
            schedule: { periods: ['FRI'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 14,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 3,
            previousRank: 2,
            updatedAt: 1628154558737,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5564344987877376,
            alias: 'i_have_a_baby',
            title: '아기가 생겼어요 [연재]',
            artists: [
              { name: '강기', role: 'writer', id: 'kangki' },
              { name: '이정', role: 'original', id: 'leejung' },
              { name: '재담미디어', role: 'publisher', id: 'jaedam' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 4,
            previousRank: 3,
            updatedAt: 1606719928639,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5162568727724032,
            alias: 'bouquet',
            title: '못난이에게 꽃다발을',
            artists: [
              { name: '사쿠라 로쿠', role: 'writer', id: 'rokusakura' },
              {
                name: '서울미디어코믹스',
                role: 'publisher',
                id: 'seoulmediacomics',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 5,
            previousRank: 690,
            updatedAt: 1626415009741,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5483951990046720,
            alias: 'sultans_flower_re',
            title: '술탄의 꽃 [개정판]',
            artists: [
              { name: '꽁', role: 'painter', id: 'ggong' },
              { name: '가하 웹툰', role: 'label', id: 'gahawebtoon' },
              { name: '춈춈', role: 'original', id: 'chyomchyom' },
              { name: '도서출판 가하', role: 'publisher', id: 'gahabooks' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 6,
            previousRank: 6,
            updatedAt: 1631598913248,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6430096279011328,
            alias: 'exonepick',
            title: '구최애로부터 비밀을 사수하라!',
            artists: [
              { name: '선마', role: 'scripter', id: 'sunma' },
              { name: '네치', role: 'painter', id: 'nechi' },
            ],
            schedule: { periods: ['THU'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 7,
            previousRank: 8,
            updatedAt: 1625537303392,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6170000663052288,
            alias: 'limit',
            title: '신데렐라 리미트',
            artists: [{ name: '깨알', role: 'writer', id: 'argok2009' }],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 8,
            previousRank: 117,
            updatedAt: 1621998410127,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6480790705209344,
            alias: 'contract_wife',
            title: '속도위반 대표님과 계약 아내 [연재]',
            artists: [
              { name: 'kkworld', role: 'painter', id: 'kkworld' },
              { name: 'shibuciyuan', role: 'painter', id: 'shibuciyuan' },
              { name: 'flower', role: 'original', id: 'flower' },
              { name: '스토리숲', role: 'publisher', id: 'storysoop' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 16,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 9,
            previousRank: 69,
            updatedAt: 1620005466771,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4907714540535808,
            alias: 'story_of_anna',
            title: '안나 이야기',
            artists: [{ name: '김지효', role: 'writer', id: 'kim_ji_hyo' }],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 29,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 10,
            previousRank: 55,
            updatedAt: 1622686784640,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 272,
            alias: 'woori',
            title: '우리사이느은',
            artists: [{ name: '이연지', role: 'writer', id: 'leegreen' }],
            schedule: { periods: ['WED'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 12,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 11,
            previousRank: 80,
            updatedAt: 1602323552147,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6694684605874176,
            alias: 'alliwantis',
            title: '내가 원하는 건',
            artists: [{ name: '정', role: 'writer', id: 'jung' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 60,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 12,
            previousRank: 7,
            updatedAt: 1611882753147,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4511761836933120,
            alias: 'hard_to_say_love',
            title: '사랑이라 하기엔 기분 나빠',
            artists: [
              { name: '모구스', role: 'writer', id: 'mogusu' },
              { name: '레진코믹스', role: 'publisher', id: 'lezhincomics' },
            ],
            schedule: { periods: ['FRI'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 13,
            previousRank: 56,
            updatedAt: 1629966790809,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4728647098630144,
            alias: 'heydragon',
            title: '있잖아요 용님!',
            artists: [
              { name: '영현', role: 'writer', id: 'younghyun' },
              { name: '키다리스튜디오', role: 'publisher', id: 'kidaristudio' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 14,
            previousRank: 9,
            updatedAt: 1625459643566,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5912387426516992,
            alias: 'between_30cm',
            title: '우리 사이 30cm',
            artists: [
              { name: 'YUJU', role: 'writer', id: 'yuju' },
              { name: '재담미디어', role: 'publisher', id: 'jaedam' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 15,
            previousRank: 27,
            updatedAt: 1630391955180,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 18,
            alias: 'giveme_ur_heart',
            title: '너의 HEART를 나에게 줄래?',
            artists: [{ name: '비아이', role: 'writer', id: 'B_i' }],
            schedule: { periods: ['THU'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 10,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 16,
            previousRank: 43,
            updatedAt: 1601537286472,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5662308507975680,
            alias: 'hayandere',
            title: '하얀데레',
            artists: [
              { name: '남별', role: 'scripter', id: 'southstar' },
              { name: '프릿슈', role: 'painter', id: 'refia' },
            ],
            schedule: { periods: ['SUN'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 7,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 17,
            previousRank: 14,
            updatedAt: 1612428328436,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5314337234812928,
            alias: 'genderis_man',
            title: '젠더리스 남자에게 사랑받고 있습니다',
            artists: [
              { name: '타메코우', role: 'writer', id: 'tamekou' },
              { name: 'AK 코믹스', role: 'label', id: 'akcomics' },
              {
                name: 'AK 커뮤니케이션즈',
                role: 'publisher',
                id: 'akcommunications',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 18,
            previousRank: 529,
            updatedAt: 1602487598708,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5905291473387520,
            alias: 'human_pervert_rd',
            title: '어차피 인간은 다 변태야 [개정판]',
            artists: [
              { name: '장미', role: 'writer', id: 'jangmi' },
              { name: '위즈덤하우스', role: 'publisher', id: 'wisdomhouse' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 19,
            previousRank: 160,
            updatedAt: 1611897725426,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
        ],
      };
    case 2:
      return {
        hasNext: true,
        count: 100,
        data: [
          {
            id: 216,
            alias: 'garden_of_the_blind',
            title: '눈 먼 정원',
            artists: [{ name: '나윤희', role: 'writer', id: 'uuuniiiii' }],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 21,
            previousRank: 125,
            updatedAt: 1623812622133,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4978865662394368,
            alias: 'miss_time',
            title: '미스타임 (Miss time) [연재]',
            artists: [
              { name: '봉구씨', role: 'scripter', id: 'bonggussi' },
              { name: '경섭', role: 'painter', id: 'kyungseop' },
              { name: '지티이엔티', role: 'publisher', id: 'gtent' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 22,
            previousRank: 68,
            updatedAt: 1614912988324,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5892678096060416,
            alias: 'angelsuse',
            title: '천사의 용도',
            artists: [{ name: '공사', role: 'writer', id: '04' }],
            schedule: { periods: ['FRI'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 65,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 23,
            previousRank: 37,
            updatedAt: 1586748326828,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 99,
            alias: 'my_secret_brother',
            title: '말할 수 없는 남매',
            artists: [{ name: '윌로우', role: 'writer', id: 'zlzydn888' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 20,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 24,
            previousRank: 12,
            updatedAt: 1610007299725,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5791250995609600,
            alias: 'sparrow',
            title: '별과 하나의 시',
            artists: [
              { name: '새별숯', role: 'scripter', id: 'birdstarcoal' },
              { name: '유나물', role: 'painter', id: 'yunamul' },
            ],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 25,
            previousRank: 10,
            updatedAt: 1618363369165,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5679225792626688,
            alias: 's_prince',
            title: '스바루 군의 절대명령!',
            artists: [
              { name: '우루 아쿠아', role: 'scripter', id: 'aquauruh' },
              { name: '우로코', role: 'painter', id: 'uroco' },
              { name: '미즈', role: 'label', id: 'miz' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 26,
            previousRank: 124,
            updatedAt: 1611559086386,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5777799590772736,
            alias: 'lotus',
            title: '연화',
            artists: [
              { name: '스튜디오 열일', role: 'writer', id: 'studioyeolil' },
              { name: '스튜디오 질풍', role: 'writer', id: 'studiojilpung' },
            ],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 27,
            previousRank: 145,
            updatedAt: 1615774378267,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6158847089901568,
            alias: 'be_careful_red_thread',
            title: '붉은 실을 조심하세요 [연재]',
            artists: [
              { name: '신지상', role: 'scripter', id: 'shinjisang' },
              { name: '유다', role: 'scripter', id: 'iudas' },
              { name: '큐민', role: 'painter', id: 'cumin' },
              { name: '천지안', role: 'original', id: 'cheonjian' },
              {
                name: '씨엔씨레볼루션㈜',
                role: 'publisher',
                id: 'cncrevolutioninc',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 28,
            previousRank: 190,
            updatedAt: 1617023844469,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6362472089255936,
            alias: 'juliet_at_a_boardingschool',
            title: '기숙학교의 줄리엣',
            artists: [
              { name: '카네다 요스케', role: 'writer', id: 'yousukekaneda' },
              { name: '학산문화사', role: 'publisher', id: 'haksan' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 29,
            previousRank: 302,
            updatedAt: 1613370272582,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4611369868197888,
            alias: 'likeyouyouyou',
            title: '너도 좋고 너도 좋고 너도 좋고',
            artists: [{ name: '이준표', role: 'writer', id: 'leehjunpyo' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 30,
            previousRank: 114,
            updatedAt: 1556855037885,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6288947252887552,
            alias: 'destiny_to_love',
            title: '게임하다 눈맞을 운명입니다 [연재]',
            artists: [
              { name: 'zuoxiaoling', role: 'scripter', id: 'zuoxiaoling' },
              { name: 'kexiaosha', role: 'painter', id: 'kexiaosha' },
              { name: '키다리스튜디오', role: 'publisher', id: 'kidaristudio' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 31,
            previousRank: 193,
            updatedAt: 1619579344481,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5112338975096832,
            alias: 'dear_first_love',
            title: '첫사랑에게 [연재]',
            artists: [
              { name: '리세', role: 'painter', id: 'leese' },
              { name: '유송주', role: 'original', id: 'yusongjoo' },
              { name: '대원씨아이', role: 'publisher', id: 'dwci' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 32,
            previousRank: 95,
            updatedAt: 1627960356436,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5203110975045632,
            alias: 'my_dads_the_boss',
            title: '우리 아빠가 대표님 이래요 [연재]',
            artists: [
              { name: '에코스튜디오', role: 'writer', id: 'echostudio' },
              { name: '엠스토리허브', role: 'publisher', id: 'mstoryhub' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 33,
            previousRank: 53,
            updatedAt: 1625022247301,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4920901046435840,
            alias: 'woman_15',
            title: '서는 여자[개정판]',
            artists: [{ name: '전호윤', role: 'writer', id: 'jeonhoyun' }],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 34,
            previousRank: 16,
            updatedAt: 1617357405624,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4535643469840384,
            alias: 'unloveable_woman',
            title: '사랑할 수 없는 그녀',
            artists: [
              { name: 'Chunfeng Studio', role: 'writer', id: 'chunfengstudio' },
              { name: 'kkworld', role: 'writer', id: 'kkworld' },
              { name: 'zero', role: 'writer', id: 'zero' },
              { name: '스토리숲', role: 'publisher', id: 'storysoop' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 35,
            previousRank: 38,
            updatedAt: 1623295311178,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6080699904098304,
            alias: 'innocent_girl',
            title: '악랄한 대표님의 순진한 그녀',
            artists: [
              { name: 'yoolook media', role: 'writer', id: 'yoolookmedia' },
              { name: '비브로스팀', role: 'publisher', id: 'vbrosteam' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 36,
            previousRank: 392,
            updatedAt: 1626763051277,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6203704861851648,
            alias: 'little_bride',
            title: '악마공작의 어린신부',
            artists: [
              { name: '조은재', role: 'scripter', id: 'joeunjae' },
              { name: '지안', role: 'painter', id: 'jiahn' },
              { name: '다온스튜디오', role: 'label', id: 'daonstudio' },
              {
                name: '다온크리에이티브',
                role: 'publisher',
                id: 'daoncreative',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 37,
            previousRank: 48,
            updatedAt: 1628563820129,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6404357085200384,
            alias: 'doridosim',
            title: '도리도심',
            artists: [{ name: '이지피', role: 'writer', id: 'egp' }],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 38,
            previousRank: 36,
            updatedAt: 1601537425692,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5665654306045952,
            alias: 'wears_mask',
            title: '악녀는 백치가면을 쓴다 [연재]',
            artists: [
              { name: '서각', role: 'scripter', id: 'seogak' },
              { name: '산', role: 'painter', id: 'san' },
              { name: '서리하', role: 'original', id: 'seoriha' },
              { name: '이코믹스', role: 'publisher', id: 'ecomix' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 39,
            previousRank: 61,
            updatedAt: 1629361607917,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
        ],
      };
    case 3:
      return {
        hasNext: true,
        count: 100,
        data: [
          {
            id: 4864814520270848,
            alias: 'black_empress',
            title: '검은머리 황녀님 [연재]',
            artists: [
              { name: '팡이', role: 'painter', id: 'pange' },
              { name: '엘리아냥', role: 'original', id: 'ellianyang' },
              {
                name: '씨엔씨레볼루션㈜',
                role: 'publisher',
                id: 'cncrevolutioninc',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 41,
            previousRank: 167,
            updatedAt: 1617024184735,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5981436817702912,
            alias: 'on_the_heel',
            title: '온 더 힐',
            artists: [
              { name: '장어진', role: 'writer', id: 'jangeojin' },
              { name: '지티이엔티', role: 'publisher', id: 'gtent' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 10,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 42,
            previousRank: 195,
            updatedAt: 1515991162615,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5452694002401280,
            alias: 'bad_hip',
            title: '엉덩이가 잘못했네 [연재]',
            artists: [
              { name: '자몽사이다(유툰)', role: 'painter', id: 'jamongcider' },
              { name: '줄라이키스', role: 'original', id: 'julyakiss' },
              { name: '비브로스팀', role: 'publisher', id: 'vbrosteam' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 43,
            previousRank: 33,
            updatedAt: 1628056571746,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6732978288328704,
            alias: 'moneylover',
            title: '너의 돈이 보여',
            artists: [
              { name: 'S리아', role: 'scripter', id: 'sreah' },
              { name: '민국23', role: 'painter', id: 'minguk23' },
            ],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 44,
            previousRank: 35,
            updatedAt: 1534398367209,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6531477824667648,
            alias: 'sflower_15',
            title: 'S플라워[개정판]',
            artists: [{ name: '진미', role: 'writer', id: 'jinmi' }],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 45,
            previousRank: 26,
            updatedAt: 1617357490370,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4562605903773696,
            alias: 'queens_secret_class',
            title: '황비님의 비밀수업 [연재]',
            artists: [
              { name: '한세람', role: 'scripter', id: 'hanseram' },
              { name: '톰', role: 'painter', id: 'tom' },
              { name: '유주얼미디어', role: 'publisher', id: 'ujewelmedia' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 46,
            previousRank: 39,
            updatedAt: 1617023222360,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5068213149040640,
            alias: 'happy_ending_life',
            title: '목숨걸고 해피엔딩',
            artists: [
              { name: '롱롱', role: 'painter', id: 'rongrong' },
              { name: '꽃닢', role: 'original', id: 'petal' },
              { name: '엠스토리허브', role: 'publisher', id: 'mstoryhub' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 47,
            previousRank: 751,
            updatedAt: 1619059508320,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5039365024382976,
            alias: 'day',
            title: '벌건 대낮',
            artists: [{ name: '최용성', role: 'writer', id: 'coast89' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 48,
            previousRank: 28,
            updatedAt: 1589961519688,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4755963969798144,
            alias: 'in_a_looked_room',
            title: '잠겨진 양호실에서 선생님과',
            artists: [
              { name: '카놀라 유', role: 'writer', id: 'canolayu' },
              { name: '미즈', role: 'label', id: 'miz' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 49,
            previousRank: 83,
            updatedAt: 1609982435763,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4786035588202496,
            alias: 'black_dragon_love',
            title: '흑룡연인',
            artists: [
              { name: '주이원', role: 'writer', id: 'jooiwon' },
              { name: '키다리스튜디오', role: 'publisher', id: 'kidaristudio' },
            ],
            schedule: { periods: ['SUN'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 50,
            previousRank: 178,
            updatedAt: 1610943310603,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4535078004785152,
            alias: 'dog_die',
            title: '개기면 죽는다',
            artists: [
              { name: '왕기대', role: 'scripter', id: 'wanggidae' },
              { name: '마야', role: 'painter', id: 'maya' },
              { name: '키다리스튜디오', role: 'publisher', id: 'kidaristudio' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 51,
            previousRank: 87,
            updatedAt: 1619579409378,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5023315744063488,
            alias: 'office_romance',
            title: '이 회사에 좋아하는 사람이 있습니다',
            artists: [
              {
                name: '에노모토 아카마루',
                role: 'writer',
                id: 'akamaruenomoto',
              },
              { name: '대원씨아이', role: 'publisher', id: 'dwci' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 52,
            previousRank: 52,
            updatedAt: 1611298014877,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6494986018816000,
            alias: 'princess_break_marriage',
            title: '왕녀님은 파혼하고 싶어',
            artists: [
              { name: 'Mii', role: 'writer', id: 'mii' },
              { name: '키다리스튜디오', role: 'publisher', id: 'kidaristudio' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 53,
            previousRank: 88,
            updatedAt: 1621326350826,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6476282696368128,
            alias: 'archers_promise',
            title: '궁서의 약속 -위장 Ω(오메가)- [연재]',
            artists: [
              { name: '시라이시 유키', role: 'writer', id: 'yukisshiraishi' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 54,
            previousRank: 17,
            updatedAt: 1627355562558,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5887090871894016,
            alias: 'sweet_kiss_sigh',
            title: '빠져드는 한숨에 달콤한 키스',
            artists: [
              { name: '키사라기 히이로', role: 'writer', id: 'kisaragihiiro' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 55,
            previousRank: 317,
            updatedAt: 1559207088548,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4989547772706816,
            alias: 'immoral_night_15',
            title: '배덕의 밤 [개정판]',
            artists: [
              { name: 'kk', role: 'painter', id: 'kk' },
              { name: '가하 웹툰', role: 'label', id: 'gahawebtoon' },
              { name: '팽유정', role: 'original', id: 'paeng' },
              { name: '도서출판 가하', role: 'publisher', id: 'gahabooks' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 56,
            previousRank: 5,
            updatedAt: 1625739135347,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5038595422617600,
            alias: 'kitty_bride',
            title: '고양이 신부',
            artists: [
              { name: '망가', role: 'scripter', id: 'manga' },
              { name: '잎', role: 'scripter', id: 'lip' },
              { name: 'dite', role: 'painter', id: 'dite' },
              { name: 'MA', role: 'painter', id: 'ma' },
              { name: '다온스튜디오', role: 'label', id: 'daonstudio' },
              {
                name: '다온크리에이티브',
                role: 'publisher',
                id: 'daoncreative',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 57,
            previousRank: 704,
            updatedAt: 1631518399530,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6023976890138624,
            alias: 'summer_winter',
            title: '한여름 이겨울',
            artists: [{ name: '군밤', role: 'writer', id: 'gb' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 58,
            previousRank: 113,
            updatedAt: 1554343203890,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5664587191156736,
            alias: 'parasite',
            title: '기생충',
            artists: [{ name: '김지효', role: 'writer', id: 'kim_ji_hyo' }],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 8,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 59,
            previousRank: 118,
            updatedAt: 1553742006975,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
        ],
      };
    case 4:
      return {
        hasNext: true,
        count: 100,
        data: [
          {
            id: 6685305436700672,
            alias: 'obscene_houseplay_15',
            title: '음란한 소꿉장난[개정판]',
            artists: [
              { name: '누끼', role: 'painter', id: 'nooki' },
              { name: '이미지프레임', role: 'label', id: 'imageframe' },
              { name: '양과람', role: 'original', id: 'yangwaram' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 61,
            previousRank: 40,
            updatedAt: 1617599477796,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5874080986038272,
            alias: 'cheongru_opera',
            title: '청루 오페라',
            artists: [
              {
                name: '사쿠라코우지 카노코',
                role: 'writer',
                id: 'sakurakoujikanoko',
              },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 62,
            previousRank: 251,
            updatedAt: 1556280202533,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4507385512394752,
            alias: 'teamleader_but_intern',
            title: '팀장이지만 인턴입니다',
            artists: [
              { name: '오마토', role: 'scripter', id: 'omato' },
              { name: '깍두', role: 'painter', id: 'ggakdoo' },
              { name: '다온스튜디오', role: 'label', id: 'daonstudio' },
              {
                name: '다온크리에이티브',
                role: 'publisher',
                id: 'daoncreative',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 63,
            previousRank: 281,
            updatedAt: 1630390775199,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5409586549424128,
            alias: 'honey_come_honey',
            title: '허니 컴 허니',
            artists: [
              { name: '시라이시 유키', role: 'writer', id: 'yukishiraishi' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 64,
            previousRank: 329,
            updatedAt: 1597918798805,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4613987880992768,
            alias: 'wickedwoman',
            title: '이번 생은 악녀로 살겠습니다 [연재]',
            artists: [
              { name: 'black', role: 'writer', id: 'black' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 65,
            previousRank: 334,
            updatedAt: 1626751288663,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4801392898801664,
            alias: 'rosy_promises',
            title: '장밋빛의 약속 [연재]',
            artists: [
              { name: '미야사카 카호', role: 'writer', id: 'miyasakakaho' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 66,
            previousRank: 445,
            updatedAt: 1627986132477,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5408762474528768,
            alias: '17_livetogether',
            title: '17세, 오늘부터 동거 시작합니다!',
            artists: [
              { name: '모모타 아코', role: 'scripter', id: 'momotaako' },
              { name: '우로코', role: 'painter', id: 'uroco' },
              { name: '미즈', role: 'label', id: 'miz' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 67,
            previousRank: 44,
            updatedAt: 1619579003874,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5274670161854464,
            alias: 'merry_go_round',
            title: '메리 고 라운드',
            artists: [{ name: '나솔', role: 'writer', id: 'nasol' }],
            schedule: { periods: ['SAT'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 68,
            previousRank: 20,
            updatedAt: 1608254172775,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6575005276635136,
            alias: 'my_witch',
            title: '나의 마녀',
            artists: [
              { name: '해윤', role: 'scripter', id: 'haeyoon' },
              { name: 'Mas', role: 'painter', id: 'mas' },
              { name: '북큐브', role: 'label', id: 'bookcube' },
              {
                name: '북큐브네트웍스',
                role: 'publisher',
                id: 'bookcubenetworks',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 69,
            previousRank: 23,
            updatedAt: 1601272716642,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4811166890655744,
            alias: 'dokkaebis_bird_re',
            title: '상냥한 도깨비의 새 [개정판]',
            artists: [
              { name: '에이비', role: 'scripter', id: 'ab' },
              { name: '8 cat', role: 'painter', id: '8cat' },
              { name: '블루픽스튜디오', role: 'label', id: 'bluepicstudio' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 70,
            previousRank: 46,
            updatedAt: 1626229657410,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4608024776867840,
            alias: '101_heroine',
            title: '101번째 여주인공',
            artists: [
              { name: '스튜디오 디', role: 'writer', id: 'studiod' },
              { name: '메나닉', role: 'original', id: 'menanic' },
              { name: '대원씨아이', role: 'publisher', id: 'dwci' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 71,
            previousRank: 229,
            updatedAt: 1617023886469,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4923723713937408,
            alias: 'how_to_seduce_him',
            title: '남주를 공략하는 방법 [연재]',
            artists: [
              { name: '희열탁마', role: 'writer', id: 'huiyeoltakma' },
              { name: '비브로스팀', role: 'publisher', id: 'vbrosteam' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 10,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 72,
            previousRank: 237,
            updatedAt: 1590479829836,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5038297021743104,
            alias: 'five_equal_parts',
            title: '5등분의 신부',
            artists: [
              { name: '하루바 네기', role: 'writer', id: 'negiharuba' },
              { name: '학산문화사', role: 'publisher', id: 'haksan' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 73,
            previousRank: 97,
            updatedAt: 1604555212438,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4692872177516544,
            alias: 'midday_meteor',
            title: '한낮의 유성',
            artists: [
              { name: '야마모리 미카', role: 'writer', id: 'yamamorimika' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 74,
            previousRank: 413,
            updatedAt: 1564377660479,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6617147453538304,
            alias: 'ninkoi',
            title: '오늘부터 너의 닌자',
            artists: [
              { name: '스즈키 줄리에타', role: 'writer', id: 'juliettasuzuki' },
              { name: '학산문화사', role: 'publisher', id: 'haksan' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 75,
            previousRank: 476,
            updatedAt: 1627527371611,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6475751743619072,
            alias: 'backstage_kiss_scene',
            title: '백스테이지 키스신',
            artists: [
              { name: '수정과', role: 'writer', id: 'soojeonggwa' },
              { name: '최도비', role: 'writer', id: 'choidobi' },
              { name: '스토리위즈', role: 'publisher', id: 'storywiz' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 76,
            previousRank: 79,
            updatedAt: 1630993782257,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4986858015883264,
            alias: 'contractual_marriage_ceo',
            title: '대표님과의 계약결혼',
            artists: [
              { name: 'animation Dong', role: 'writer', id: 'animationdong' },
              { name: 'Weibo Comics', role: 'writer', id: 'weibocomics' },
              { name: '엠젯패밀리', role: 'publisher', id: 'mzfamily' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 77,
            previousRank: 634,
            updatedAt: 1624861622521,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6606572140167168,
            alias: 'vice_president',
            title: '거만한 부사장에게 잡혔습니다',
            artists: [
              { name: '이시카와 유키', role: 'scripter', id: 'yukiishikawa' },
              { name: '모치즈키 사나', role: 'painter', id: 'sanamochizuki' },
              { name: '지티이엔티', role: 'publisher', id: 'gtent' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 78,
            previousRank: 916,
            updatedAt: 1620118211510,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6222637011828736,
            alias: 'secretmylove',
            title: '비밀스러운 짝사랑',
            artists: [{ name: '정', role: 'writer', id: 'jung' }],
            schedule: { periods: ['THU'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 79,
            previousRank: 107,
            updatedAt: 1621998422401,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
        ],
      };
    case 5:
      return {
        hasNext: true,
        count: 100,
        data: [
          {
            id: 5382463174868992,
            alias: 'oneplusone',
            title: '1 더하기 1은',
            artists: [{ name: '소루', role: 'writer', id: 'soru' }],
            schedule: { periods: ['SUN'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 81,
            previousRank: 81,
            updatedAt: 1625022219927,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5847030093185024,
            alias: 'cute_jung',
            title: '잔망스러운 정주임',
            artists: [
              { name: '이현민', role: 'scripter', id: 'hyunmin' },
              { name: 'miyune', role: 'painter', id: 'miyune' },
              { name: 'JQ스튜디오', role: 'publisher', id: 'jqstudio' },
            ],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 16,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 82,
            previousRank: 45,
            updatedAt: 1610943112320,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5059460702011392,
            alias: '685',
            title: '685일',
            artists: [{ name: '새얀', role: 'writer', id: 'seyean' }],
            schedule: { periods: ['SUN'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 8,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 83,
            previousRank: 49,
            updatedAt: 1606983467727,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6131691861311488,
            alias: 'girl_birth',
            title: '탄생소녀',
            artists: [
              { name: '애플링', role: 'scripter', id: 'kyokyokyo' },
              { name: '뿔사슴', role: 'painter', id: 'antlerdeer' },
            ],
            schedule: { periods: ['WED'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 5,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 84,
            previousRank: 21,
            updatedAt: 1544065200786,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6466786480095232,
            alias: 'otakoi',
            title: '오타쿠에게 사랑은 어려워',
            artists: [
              { name: '후지타', role: 'writer', id: 'fujita' },
              { name: '레진코믹스', role: 'publisher', id: 'lezhincomics' },
            ],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'scheduled',
            isPrint: false,
            currentRank: 85,
            previousRank: 82,
            updatedAt: 1626671868338,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6461632918126592,
            alias: 'space',
            title: '우주인(Would you in?)',
            artists: [{ name: '피티', role: 'writer', id: 'peatea' }],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 6,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 86,
            previousRank: 122,
            updatedAt: 1610005817868,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 5943773066559488,
            alias: 'christmas_in_the_elevator',
            title: '엘리베이터에서 하룻밤',
            artists: [{ name: '김지효', role: 'writer', id: 'kim_ji_hyo' }],
            schedule: { periods: ['MON'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 2,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 87,
            previousRank: 50,
            updatedAt: 1550042743798,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6066872002936832,
            alias: 'xx_teacher',
            title: '선생님, xx라는 게 진짜예요?',
            artists: [
              { name: '와타세 하나', role: 'writer', id: 'hanawatase' },
              { name: '미즈', role: 'label', id: 'miz' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 88,
            previousRank: 133,
            updatedAt: 1614143327298,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 55,
            alias: 'musician',
            title: '뮤지션',
            artists: [{ name: '단추', role: 'writer', id: 'button' }],
            schedule: { periods: ['SUN'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 9,
            contentsState: 'completed',
            isPrint: false,
            currentRank: 89,
            previousRank: 85,
            updatedAt: 1550051611923,
            print: false,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6069041722294272,
            alias: 'av_writer',
            title: '경험은 있어야죠, 작가님!',
            artists: [
              { name: '카나모리 케이타', role: 'writer', id: 'keitakanamori' },
              { name: '미즈', role: 'label', id: 'miz' },
              { name: '넥스큐브', role: 'publisher', id: 'nexcube' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 90,
            previousRank: 152,
            updatedAt: 1614143194620,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4866953452781568,
            alias: 'queen_of_other_world',
            title: '이세계의 황비',
            artists: [
              { name: '임서림', role: 'scripter', id: 'limseolim' },
              { name: '이영유', role: 'painter', id: 'leeyoungyu' },
              {
                name: '디앤씨웹툰비즈',
                role: 'publisher',
                id: 'dncwebtoonbiz',
              },
            ],
            schedule: { periods: ['TUE'], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 91,
            previousRank: 165,
            updatedAt: 1617023790741,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6552050783092736,
            alias: 'turnoff_tv',
            title: 'TV를 꺼드립니다',
            artists: [
              { name: 'Lunar Phase', role: 'scripter', id: 'lunarphase' },
              { name: 'sage', role: 'painter', id: 'sage' },
              { name: '디투컴퍼니', role: 'publisher', id: 'd2company' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 92,
            previousRank: 169,
            updatedAt: 1561352363621,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4904857069813760,
            alias: 'ouran_host_club',
            title: '오란고교 호스트부',
            artists: [
              { name: '하토리 비스코', role: 'writer', id: 'biscohatori' },
              { name: '학산문화사', role: 'publisher', id: 'haksan' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 93,
            previousRank: 172,
            updatedAt: 1626069523290,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6245541874302976,
            alias: 'spoonful_of_your_heart',
            title: '그대 마음 한 스푼 [연재]',
            artists: [
              { name: 'JB', role: 'scripter', id: 'jb' },
              { name: 'STEM', role: 'painter', id: 'stem' },
              { name: '서경', role: 'original', id: 'seokyeong' },
              { name: '이코믹스', role: 'publisher', id: 'ecomix' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 94,
            previousRank: 58,
            updatedAt: 1604654701144,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4732211905757184,
            alias: 'runaway_wife',
            title: '대표님, 사모님이 도망가요 [연재]',
            artists: [
              { name: 'Hongshu', role: 'painter', id: 'hongshu' },
              { name: 'Anyouran', role: 'original', id: 'anyouran' },
              { name: '스토리숲', role: 'publisher', id: 'storySoop' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 21,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 95,
            previousRank: 273,
            updatedAt: 1625022275518,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4871738561527808,
            alias: 'we_love',
            title: '우이 러브 -순수한 사랑 이야기-',
            artists: [
              {
                name: '호시모리 유키모',
                role: 'writer',
                id: 'hoshimoriyukimo',
              },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 96,
            previousRank: 279,
            updatedAt: 1565253612140,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 568,
            alias: 'fujiyama',
            title: '후지야마는 사춘기',
            artists: [
              { name: '오지로 마코토', role: 'writer', id: 'ojiromakoto' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 1,
            contentsState: 'completed',
            isPrint: true,
            currentRank: 97,
            previousRank: 327,
            updatedAt: 1512010804599,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 4589931149197312,
            alias: 'black_maid',
            title: '사신 도련님과 검은 메이드 [연재]',
            artists: [
              { name: '이노우에 코하루', role: 'writer', id: 'koharuinoue' },
              { name: 'DCW', role: 'publisher', id: 'dcw' },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 4,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 98,
            previousRank: 74,
            updatedAt: 1593584168441,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
          {
            id: 6035313625464832,
            alias: 'mprobable_reason',
            title: '이율같지 않은 이유',
            artists: [
              { name: 'RAY', role: 'scripter', id: 'ray' },
              { name: '치구리', role: 'painter', id: 'chiguri' },
              {
                name: '서울미디어코믹스',
                role: 'publisher',
                id: 'seoulmediacomics',
              },
            ],
            schedule: { periods: [], anchor: 0 },
            genres: ['romance'],
            freedEpisodeSize: 3,
            contentsState: 'scheduled',
            isPrint: true,
            currentRank: 99,
            previousRank: 94,
            updatedAt: 1624864647474,
            print: true,
            thumbnailSrc: 'https://dummyimage.com/80x120/c2c2c2/000000.jpg',
          },
        ],
      };
    default:
      return {
        count: 0,
        hasNext: false,
        data: [],
      };
  }
}
